name: Issue Creation Tracker
on:
  issues:
    types: [opened]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Google Chat Notification
      run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
          echo "Issue labels: ${{ github.event.issue.labels }}"
