name: Issue Creation Tracker
on:
  issues:
    types: [opened, edited]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git Issue Details
      run: |
          echo "Issue creator: ${{ github.event.issue.user.login }}"
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Issue url: ${{ github.event.issue.html_url }}"
          echo "Issue body: ${{ github.event.issue.body }}"
          echo "Assigned labels: " ${{ join(github.event.issue.labels.*.name) }}
          echo "Assignees: " ${{ join(github.event.issue.assignees.*.login) }}
    - name: Google Chat Notification
      run: |
          curl --location --request POST '${{ secrets.WEBHOOK }}&threadKey=dep_updater' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "cards": [
                  {
                      "header": {
                          "title": "Issue Tracker",
                          "subtitle": "Issue No: #${{ github.event.issue.number }}"
                      },
                      "sections": [
                          {
                              "widgets": [
                                  {
                                      "textParagraph": {
                                          "text": "<b>Creator:</b> <br>${{ github.event.issue.user.login }}</br>"

                                      }
                                  },
                                  {
                                     "keyValue": {
                                          "topLabel": "Issue URL:",
                                          "content": "Issue URL:",
                                          "contentMultiline": "false",
                                          "bottomLabel": "",
                                          "button": {
                                              "textButton": {
                                                "text": "VIEW",
                                                "onClick": {
                                                    "openLink": {
                                                          "url": ${{ github.event.issue.html_url }}
                                                      }
                                                 }
                                               }
                                           }
                                      }
                                   }
                              ]
                          }
                      ]
                  }
              ]
          }'
